export default {
  ART_ADD: 'ART_ADD',
  ART_ADD_BATCH: 'ART_ADD_BATCH',
  WHO_ADD_INFO: 'WHO_ADD_INFO',
  SET_FILTER: 'SET_FILTER',
  REMOVE_FILTER: 'REMOVE_FILTER',
  CLEAR_FILTERS: 'CLEAR_FILTERS',
  EVENT_CLICK_AWAY: 'EVENT_CLICK_AWAY'
}
